# Generated by Django 6.0.5 on 2026-05-08 15:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Дата"),
                ),
                (
                    "morning_gratitude",
                    models.TextField(
                        blank=True,
                        help_text="3-5 вещей за которые вы благодарны",
                        verbose_name="За что я благодарен?",
                    ),
                ),
                (
                    "morning_affirmation",
                    models.CharField(
                        blank=True,
                        help_text="Позитивное утверждение о себе",
                        max_length=500,
                        verbose_name="Моя аффирмация",
                    ),
                ),
                (
                    "morning_goals",
                    models.TextField(
                        blank=True,
                        help_text="2-3 ключевые задачи на день",
                        verbose_name="Что сделает сегодняшний день великим?",
                    ),
                ),
                (
                    "evening_wins",
                    models.TextField(
                        blank=True,
                        help_text="Чего я достиг сегодня?",
                        verbose_name="Мои сегодняшние победы",
                    ),
                ),
                (
                    "evening_improvement",
                    models.TextField(
                        blank=True,
                        help_text="Уроки на сегодня",
                        verbose_name="Что я мог сделать лучше?",
                    ),
                ),
                (
                    "evening_lesson",
                    models.TextField(
                        blank=True,
                        help_text="Новые инсайты и открытия",
                        verbose_name="Чему я научился сегодня?",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("great", "Отличное 🌟"),
                            ("good", "Хорошее 😊"),
                            ("normal", "Нормальное 😐"),
                            ("sad", "Грустное 😔"),
                            ("bad", "Плохое 😢"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Настроение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в дневнике успеха",
                "verbose_name_plural": "Записи в дневнике успеха",
                "ordering": ["-date"],
                "unique_together": {("author", "date")},
            },
        ),
    ]
